[workspace]
authors = ["Damineni Hemanth Satya Veer <hemanthdamineni@gmail.com>"]
channels = ["conda-forge"]
name = "Lab 10"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
streamlit = ">=1.50.0,<2"
plotly = ">=6.3.1,<7"
wordcloud = ">=1.9.4,<2"
